// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechMove_Global_Logistic_Management_System.Data;

#nullable disable

namespace TechMove_Global_Logistic_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516153911_CreateContractTable")]
    partial class CreateContractTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ClientModel", b =>
                {
                    b.Property<int>("Client_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("country");

                    b.Property<string>("Email_Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email_Address");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("first_Name");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("last_Name");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("phone_Number");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("region");

                    b.HasKey("Client_Id");

                    b.ToTable("tblClients");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ContractModel", b =>
                {
                    b.Property<int>("Contract_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contract_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Contract_Id"));

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_Date");

                    b.Property<string>("Service_Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("service_Level");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_Date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_Status");

                    b.Property<int?>("Support_Doc_Id")
                        .HasColumnType("int");

                    b.HasKey("Contract_Id");

                    b.HasIndex("Support_Doc_Id");

                    b.ToTable("tblContracts");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.SupportDocumentModel", b =>
                {
                    b.Property<int>("Support_Doc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("support_Doc_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Support_Doc_Id"));

                    b.Property<string>("File_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_Name");

                    b.Property<string>("File_Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_Path");

                    b.HasKey("Support_Doc_Id");

                    b.ToTable("tblSupportDocuments");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ContractModel", b =>
                {
                    b.HasOne("TechMove_Global_Logistic_Management_System.Models.SupportDocumentModel", "SupportDocument")
                        .WithMany()
                        .HasForeignKey("Support_Doc_Id");

                    b.Navigation("SupportDocument");
                });
#pragma warning restore 612, 618
        }
    }
}
