// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechMove_Global_Logistic_Management_System.Data;

#nullable disable

namespace TechMove_Global_Logistic_Management_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.AdminModel", b =>
                {
                    b.Property<int>("Admin_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Admin_Id"));

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_On");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("first_Name");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("last_Name");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("user_Name");

                    b.HasKey("Admin_Id");

                    b.ToTable("tblAdmin", (string)null);
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.AuditLogModel", b =>
                {
                    b.Property<int>("Audit_Log_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("audit_Log_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Audit_Log_Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("action");

                    b.Property<int>("Admin_Id")
                        .HasColumnType("int")
                        .HasColumnName("admin_Id");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_On");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("IP_Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_Address");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("module");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("Audit_Log_Id");

                    b.HasIndex("Admin_Id");

                    b.ToTable("tblAuditLogs", (string)null);
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ClientModel", b =>
                {
                    b.Property<int>("Client_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Client_Id"));

                    b.Property<int>("Admin_Id")
                        .HasColumnType("int")
                        .HasColumnName("admin_Id");

                    b.Property<string>("Client_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("client_Name");

                    b.Property<string>("Contact_Person")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("contact_Person");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("country");

                    b.Property<string>("Email_Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email_Address");

                    b.Property<string>("Phone_Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_Number");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("region");

                    b.HasKey("Client_Id");

                    b.HasIndex("Admin_Id");

                    b.ToTable("tblClients", (string)null);
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ContractModel", b =>
                {
                    b.Property<int>("Contract_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contract_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Contract_Id"));

                    b.Property<int>("Admin_Id")
                        .HasColumnType("int")
                        .HasColumnName("admin_Id");

                    b.Property<int>("Client_Id")
                        .HasColumnType("int")
                        .HasColumnName("client_Id");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_Date");

                    b.Property<string>("Service_Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("service_Level");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_Date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contract_Status");

                    b.Property<int?>("Support_Doc_Id")
                        .HasColumnType("int")
                        .HasColumnName("support_Doc_Id");

                    b.HasKey("Contract_Id");

                    b.HasIndex("Admin_Id");

                    b.HasIndex("Client_Id");

                    b.HasIndex("Support_Doc_Id");

                    b.ToTable("tblContracts", (string)null);
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ServiceRequestModel", b =>
                {
                    b.Property<int>("Service_Request_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("service_Request_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Service_Request_Id"));

                    b.Property<int>("Contract_Id")
                        .HasColumnType("int")
                        .HasColumnName("contract_Id");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_On");

                    b.Property<string>("Currency_Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency_Code");

                    b.Property<decimal>("Exchange_Rate")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("exchange_Rate");

                    b.Property<string>("Service_Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("service_Description");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("USD_Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("usd_Amount");

                    b.Property<decimal>("ZAR_Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("zar_Amount");

                    b.HasKey("Service_Request_Id");

                    b.HasIndex("Contract_Id");

                    b.ToTable("tblServiceRequests", (string)null);
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.SupportDocumentModel", b =>
                {
                    b.Property<int>("Support_Doc_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("support_Doc_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Support_Doc_Id"));

                    b.Property<string>("File_Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_Name");

                    b.Property<string>("File_Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_Path");

                    b.Property<string>("File_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("file_Type");

                    b.Property<DateTime>("Uploaded_On")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_On");

                    b.HasKey("Support_Doc_Id");

                    b.ToTable("tblSupportDocuments", (string)null);
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.AuditLogModel", b =>
                {
                    b.HasOne("TechMove_Global_Logistic_Management_System.Models.AdminModel", "Admin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("Admin_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ClientModel", b =>
                {
                    b.HasOne("TechMove_Global_Logistic_Management_System.Models.AdminModel", "Admin")
                        .WithMany("Clients")
                        .HasForeignKey("Admin_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ContractModel", b =>
                {
                    b.HasOne("TechMove_Global_Logistic_Management_System.Models.AdminModel", "Admin")
                        .WithMany("Contracts")
                        .HasForeignKey("Admin_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TechMove_Global_Logistic_Management_System.Models.ClientModel", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TechMove_Global_Logistic_Management_System.Models.SupportDocumentModel", "SupportDocument")
                        .WithMany("Contracts")
                        .HasForeignKey("Support_Doc_Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Admin");

                    b.Navigation("Client");

                    b.Navigation("SupportDocument");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ServiceRequestModel", b =>
                {
                    b.HasOne("TechMove_Global_Logistic_Management_System.Models.ContractModel", "Contract")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("Contract_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.AdminModel", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Clients");

                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ClientModel", b =>
                {
                    b.Navigation("Contracts");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.ContractModel", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("TechMove_Global_Logistic_Management_System.Models.SupportDocumentModel", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
